name: apple_vision_hand_3d
description: A Flutter plugin to use Apple Vision Hand Detection to detect a single hand and fingers in an image or video stream, and identify key distal features.
version: 0.0.1
homepage: https://github.com/Knightro63/apple_vision/tree/main/packages/apple_vision_hand

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  apple_vision_commons: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: AppleVisionHand3DPlugin
        sharedDarwinSource: true
      ios:
        pluginClass: AppleVisionHand3DPlugin
        sharedDarwinSource: true
