name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  apple_vision_face:
    path: ../../apple_vision_face
  camera_macos:
    git:
      url: https://github.com/Knightro63/camera_macos.git
  camera: ^0.10.5+2
  cupertino_icons: ^1.0.2
  image: ^4.0.02

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
