name: apple_vision_image_classification
description: A Flutter plugin to use Apple Vision Image Classification the classifies an image.
version: 0.0.1
homepage: https://github.com/Knightro63/apple_vision/tree/main/packages/apple_vision_image_classification

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  apple_vision_commons: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: AppleVisionImageClassificationPlugin
        sharedDarwinSource: true
      ios:
        pluginClass: AppleVisionImageClassificationPlugin
        sharedDarwinSource: true

  
