name: apple_vision_scanner
description: A Flutter plugin to use Apple Vision Barcode Scanning to read data encoded using most standard barcode formats.
version: 0.0.1
homepage: https://github.com/Knightro63/apple_vision/tree/main/packages/apple_vision_scanner

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  apple_vision_commons: ^0.0.1

dependency_overrides:
  apple_vision_commons:
    path: ../apple_vision_commons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: AppleVisionScannerPlugin
