name: apple_vision_lift_subjects
description: A Flutter plugin to use Apple Vision Lift Subject to extract objects in real time from a continuous video or static image.
version: 0.0.2
homepage: https://github.com/Knightro63/apple_vision/tree/main/packages/apple_vision_lift_subjects

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  apple_vision_commons: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: AppleVisionLiftSubjectsPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: AppleVisionLiftSubjectsPlugin
        sharedDarwinSource: true
