name: apple_vision_object
description: A Flutter plugin to use Apple Vision Object Detection and Tracking to detect and track objects in an image or live camera feed.
version: 0.0.1
homepage: https://github.com/Knightro63/apple_vision/tree/main/packages/apple_vision_object

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  apple_vision_commons: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: AppleVisionObjectPlugin
