name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  apple_vision_lift_subjects:
    path: ../../apple_vision_lift_subjects
  cupertino_icons: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/WaterOnTheMoonFull.jpg
    - assets/rose.jpg
    - assets/human.png
    - assets/flowers.jpg