name: apple_vision
description: A Flutter plugin to use all API's from Apple vision made for osx and ios.
version: 0.0.2
homepage: https://github.com/Knightro63/apple_vision/tree/main/packages/apple_vision

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  apple_vision_animal_pose: ^0.0.1
  apple_vision_commons: ^0.0.1
  apple_vision_face: ^0.0.2
  apple_vision_face_detection: ^0.0.1
  apple_vision_hand: ^0.0.2
  apple_vision_image_classification: ^0.0.1
  apple_vision_object: ^0.0.1
  apple_vision_object_tracking: ^0.0.1
  apple_vision_pose: ^0.0.2
  apple_vision_recognize_text: ^0.0.1
  apple_vision_selfie: ^0.0.1

# dependency_overrides:
#   apple_vision_commons:
#     path: ../apple_vision_commons
#   apple_vision_face:
#     path: ../apple_vision_face
#   apple_vision_pose:
#     path: ../apple_vision_pose
#   apple_vision_hand:
#     path: ../apple_vision_hand
#   apple_vision_object:
#     path: ../apple_vision_object
#   apple_vision_scanner:
#     path: ../apple_vision_scanner

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3