name: apple_vision_commons
description: A Flutter plugin with commons files to implement Apple vision made for osx.
version: 0.0.1
homepage: https://github.com/Knightro63/apple_vision/tree/main/packages/apple_vision_commons

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
