name: apple_vision_face_detection
description: A Flutter plugin to use Apple Vision Face Detection to find faces in an image or live camera feed.
version: 0.0.2
homepage: https://github.com/Knightro63/apple_vision/tree/main/packages/apple_vision_object

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  apple_vision_commons: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: AppleVisionFaceDetectionPlugin
        sharedDarwinSource: true
      ios:
        pluginClass: AppleVisionFaceDetectionPlugin
        sharedDarwinSource: true
