name: apple_vision_face
description: A Flutter plugin to use Apple Vision Face Detection to detect faces in an image or video stream, identify key facial features, and get the contours of detected faces.
version: 0.0.2
homepage: https://github.com/Knightro63/apple_vision/tree/main/packages/apple_vision_face

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  apple_vision_commons: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: AppleVisionFacePlugin
        sharedDarwinSource: true
      macos:
        pluginClass: AppleVisionFacePlugin
        sharedDarwinSource: true
